'use client'

import { useState, useEffect, useRef } from 'react'
import FormattedText from './FormattedText'

interface NotesModeProps {
  topic: string
  onClose: () => void
}

export default function NotesMode({ topic, onClose }: NotesModeProps) {
  const [notes, setNotes] = useState<string>('')
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [isDownloading, setIsDownloading] = useState(false)
  const hasFetched = useRef(false)
  const notesRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (hasFetched.current) return
    hasFetched.current = true
    fetchNotes()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const fetchNotes = async () => {
    try {
      setIsLoading(true)
      setError(null)

      const res = await fetch('/api/notes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic }),
      })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || 'Failed to generate notes')
      }

      setNotes(data.notes)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load notes')
    } finally {
      setIsLoading(false)
    }
  }

  const handleDownloadPDF = async () => {
    setIsDownloading(true)

    try {
      // Dynamic import for client-side only
      const html2canvas = (await import('html2canvas')).default
      const { jsPDF } = await import('jspdf')

      if (!notesRef.current) return

      // Create a temporary container with print-friendly styles
      const printContainer = document.createElement('div')
      printContainer.innerHTML = notesRef.current.innerHTML
      printContainer.style.width = '595px' // A4 width in points
      printContainer.style.padding = '40px'
      printContainer.style.background = 'white'
      printContainer.style.position = 'absolute'
      printContainer.style.left = '-9999px'
      printContainer.style.fontFamily = 'Arial, sans-serif'
      document.body.appendChild(printContainer)

      // Generate canvas
      const canvas = await html2canvas(printContainer, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
      })

      document.body.removeChild(printContainer)

      // Calculate dimensions
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF('p', 'mm', 'a4')
      const pdfWidth = pdf.internal.pageSize.getWidth()
      const pdfHeight = pdf.internal.pageSize.getHeight()
      const imgWidth = canvas.width
      const imgHeight = canvas.height
      const ratio = Math.min(pdfWidth / imgWidth, pdfHeight / imgHeight)
      const imgX = (pdfWidth - imgWidth * ratio) / 2
      const imgY = 10

      // Check if we need multiple pages
      const scaledHeight = imgHeight * ratio * (pdfWidth / imgWidth)
      const pageHeight = pdfHeight - 20 // margin

      if (scaledHeight <= pageHeight) {
        // Single page
        pdf.addImage(imgData, 'PNG', imgX, imgY, imgWidth * ratio * 0.95, imgHeight * ratio * 0.95)
      } else {
        // Multi-page support
        let heightLeft = scaledHeight
        let position = 0

        pdf.addImage(imgData, 'PNG', imgX, imgY, pdfWidth - 20, scaledHeight)
        heightLeft -= pageHeight

        while (heightLeft > 0) {
          position = heightLeft - scaledHeight
          pdf.addPage()
          pdf.addImage(imgData, 'PNG', imgX, position + 10, pdfWidth - 20, scaledHeight)
          heightLeft -= pageHeight
        }
      }

      // Add disclaimer at the bottom of the last page
      const lastPage = pdf.getNumberOfPages()
      pdf.setPage(lastPage)
      pdf.setFontSize(8)
      pdf.setTextColor(128, 128, 128)
      const disclaimer = 'Disclaimer: These AI-generated notes are for revision purposes only and may not be comprehensive. Please verify with official sources and search for additional resources as needed.'
      const disclaimerLines = pdf.splitTextToSize(disclaimer, pdfWidth - 30)
      pdf.text(disclaimerLines, 15, pdfHeight - 15)

      // Add watermark
      pdf.setFontSize(10)
      pdf.setTextColor(100, 100, 100)
      pdf.text('Generated by BloomGuide', 15, pdfHeight - 8)

      // Download
      pdf.save(`${topic.replace(/[^a-zA-Z0-9]/g, '_')}_notes.pdf`)
    } catch (err) {
      console.error('PDF generation error:', err)
      // Fallback: Download as text file
      downloadAsText()
    } finally {
      setIsDownloading(false)
    }
  }

  const downloadAsText = () => {
    const disclaimer = '\n\n---\nDisclaimer: These AI-generated notes are for revision purposes only and may not be comprehensive. Please verify with official sources and search for additional resources as needed.\n\nGenerated by BloomGuide'
    const blob = new Blob([notes + disclaimer], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${topic.replace(/[^a-zA-Z0-9]/g, '_')}_notes.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  // Convert markdown to styled content for display
  const renderNotes = (content: string) => {
    const lines = content.split('\n')
    const elements: JSX.Element[] = []
    let listItems: string[] = []
    let listType: 'ul' | 'ol' | null = null

    const flushList = () => {
      if (listItems.length > 0 && listType) {
        if (listType === 'ul') {
          elements.push(
            <ul key={`list-${elements.length}`} className="list-disc list-inside space-y-1 mb-4 text-gray-700">
              {listItems.map((item, i) => (
                <li key={i}><FormattedText text={item} /></li>
              ))}
            </ul>
          )
        } else {
          elements.push(
            <ol key={`list-${elements.length}`} className="list-decimal list-inside space-y-1 mb-4 text-gray-700">
              {listItems.map((item, i) => (
                <li key={i}><FormattedText text={item} /></li>
              ))}
            </ol>
          )
        }
        listItems = []
        listType = null
      }
    }

    lines.forEach((line, idx) => {
      // Handle headers
      if (line.startsWith('# ')) {
        flushList()
        elements.push(
          <h1 key={idx} className="text-2xl font-bold text-gray-900 mb-4 pb-2 border-b border-gray-200">
            {line.slice(2)}
          </h1>
        )
      } else if (line.startsWith('## ')) {
        flushList()
        elements.push(
          <h2 key={idx} className="text-xl font-semibold text-gray-900 mt-6 mb-3">
            {line.slice(3)}
          </h2>
        )
      } else if (line.startsWith('### ')) {
        flushList()
        elements.push(
          <h3 key={idx} className="text-lg font-medium text-gray-800 mt-4 mb-2">
            {line.slice(4)}
          </h3>
        )
      }
      // Handle bullet points
      else if (line.match(/^[-*] /)) {
        if (listType !== 'ul') {
          flushList()
          listType = 'ul'
        }
        listItems.push(line.slice(2))
      }
      // Handle numbered lists
      else if (line.match(/^\d+\. /)) {
        if (listType !== 'ol') {
          flushList()
          listType = 'ol'
        }
        listItems.push(line.replace(/^\d+\. /, ''))
      }
      // Handle code blocks
      else if (line.startsWith('```')) {
        flushList()
        // Skip the opening/closing backticks, they're handled by FormattedText
      }
      // Handle empty lines
      else if (line.trim() === '') {
        flushList()
      }
      // Handle regular paragraphs
      else {
        flushList()
        elements.push(
          <p key={idx} className="text-gray-700 mb-3 leading-relaxed">
            <FormattedText text={line} />
          </p>
        )
      }
    })

    flushList()
    return elements
  }

  if (isLoading) {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-2xl p-8 max-w-lg w-full text-center">
          <div className="w-16 h-16 border-4 border-teal-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-900">Generating Notes...</h3>
          <p className="text-gray-500 text-sm mt-2">Creating comprehensive study notes for {topic}</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-2xl p-8 max-w-lg w-full text-center">
          <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </div>
          <h3 className="text-lg font-semibold text-gray-900">Failed to Generate Notes</h3>
          <p className="text-gray-500 text-sm mt-2">{error}</p>
          <div className="flex gap-3 justify-center mt-6">
            <button
              onClick={onClose}
              className="px-4 py-2 text-gray-600 hover:text-gray-800"
            >
              Cancel
            </button>
            <button
              onClick={() => {
                hasFetched.current = false
                fetchNotes()
              }}
              className="px-4 py-2 bg-teal-500 text-white rounded-lg hover:bg-teal-600"
            >
              Try Again
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between bg-gradient-to-r from-teal-500 to-cyan-500">
          <div className="text-white">
            <p className="font-medium">Study Notes</p>
            <p className="text-xs opacity-90">{topic}</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadPDF}
              disabled={isDownloading}
              className="flex items-center gap-2 px-4 py-2 bg-white/20 hover:bg-white/30 text-white rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
            >
              {isDownloading ? (
                <>
                  <svg className="w-4 h-4 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                  Generating...
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Download PDF
                </>
              )}
            </button>
            <button
              onClick={onClose}
              className="p-2 text-white/80 hover:text-white rounded-lg"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Notes Content */}
        <div className="flex-1 overflow-y-auto p-6" ref={notesRef}>
          <div className="prose prose-gray max-w-none">
            {renderNotes(notes)}
          </div>
        </div>

        {/* Disclaimer Footer */}
        <div className="px-6 py-3 bg-amber-50 border-t border-amber-100">
          <p className="text-xs text-amber-700 flex items-start gap-2">
            <svg className="w-4 h-4 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <span>
              <strong>Disclaimer:</strong> These AI-generated notes are for revision purposes only and may not be comprehensive.
              Please verify with official sources and search for additional resources as needed.
            </span>
          </p>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-gray-100 flex items-center justify-between bg-white">
          <button
            onClick={downloadAsText}
            className="text-sm text-gray-500 hover:text-gray-700 flex items-center gap-1"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download as Markdown
          </button>
          <button
            onClick={onClose}
            className="px-6 py-2 bg-gray-900 text-white rounded-xl hover:bg-gray-800 font-medium"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  )
}
