'use client'

import { useState, useEffect, useRef } from 'react'
import MathText from './MathText'
import { apiPost } from '@/lib/api'

interface NotesModeProps {
  topic: string
  onClose: () => void
}

export default function NotesMode({ topic, onClose }: NotesModeProps) {
  const [notes, setNotes] = useState<string>('')
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [isDownloading, setIsDownloading] = useState(false)
  const hasFetched = useRef(false)
  const notesRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (hasFetched.current) return
    hasFetched.current = true
    fetchNotes()
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const fetchNotes = async () => {
    try {
      setIsLoading(true)
      setError(null)

      const res = await apiPost('/api/notes', { topic })

      const data = await res.json()

      if (!res.ok) {
        throw new Error(data.error || 'Failed to generate notes')
      }

      setNotes(data.notes)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load notes')
    } finally {
      setIsLoading(false)
    }
  }

  // Convert LaTeX math to readable plain text for PDF
  const convertLatexToReadable = (latex: string): string => {
    return latex
      .replace(/\\times/g, '×')
      .replace(/\\div/g, '÷')
      .replace(/\\pm/g, '±')
      .replace(/\\cdot/g, '·')
      .replace(/\\neq/g, '≠')
      .replace(/\\leq/g, '≤')
      .replace(/\\geq/g, '≥')
      .replace(/\\approx/g, '≈')
      .replace(/\\alpha/g, 'α')
      .replace(/\\beta/g, 'β')
      .replace(/\\gamma/g, 'γ')
      .replace(/\\delta/g, 'δ')
      .replace(/\\theta/g, 'θ')
      .replace(/\\lambda/g, 'λ')
      .replace(/\\mu/g, 'μ')
      .replace(/\\pi/g, 'π')
      .replace(/\\sigma/g, 'σ')
      .replace(/\\phi/g, 'φ')
      .replace(/\\omega/g, 'ω')
      .replace(/\\Delta/g, 'Δ')
      .replace(/\\Sigma/g, 'Σ')
      .replace(/\\infty/g, '∞')
      .replace(/\\sum/g, 'Σ')
      .replace(/\\int/g, '∫')
      .replace(/\\rightarrow/g, '→')
      .replace(/\\leftarrow/g, '←')
      .replace(/\\frac\{([^}]+)\}\{([^}]+)\}/g, '($1/$2)')
      .replace(/\\sqrt\{([^}]+)\}/g, '√($1)')
      .replace(/\^2/g, '²')
      .replace(/\^3/g, '³')
      .replace(/\^n/g, 'ⁿ')
      .replace(/\^\{([^}]+)\}/g, '^$1')
      .replace(/_\{([^}]+)\}/g, '_$1')
      .replace(/\\text\{([^}]+)\}/g, '$1')
      .replace(/\\left/g, '')
      .replace(/\\right/g, '')
      .replace(/\\/g, '')
  }

  // Process text to convert math delimiters
  const processTextForPDF = (text: string): string => {
    return text
      .replace(/\$\$([^$]+)\$\$/g, (_, math) => convertLatexToReadable(math.trim()))
      .replace(/\$([^$]+)\$/g, (_, math) => convertLatexToReadable(math))
  }

  const handleDownloadPDF = async () => {
    setIsDownloading(true)

    try {
      const { jsPDF } = await import('jspdf')

      const pdf = new jsPDF('p', 'mm', 'a4')
      const pageWidth = pdf.internal.pageSize.getWidth()
      const pageHeight = pdf.internal.pageSize.getHeight()
      const margin = 20
      const contentWidth = pageWidth - margin * 2
      const lineHeight = 6
      const footerHeight = 25

      let y = margin
      let pageNum = 1

      const addNewPage = () => {
        // Add footer to current page
        pdf.setFontSize(8)
        pdf.setTextColor(130, 130, 130)
        pdf.text('AI-generated notes for revision. Verify with official sources.', margin, pageHeight - 15)
        pdf.text('Generated by BloomGuide', margin, pageHeight - 10)
        pdf.text(`Page ${pageNum}`, pageWidth - margin - 15, pageHeight - 10)

        pdf.addPage()
        pageNum++
        y = margin
      }

      const checkPageBreak = (height: number) => {
        if (y + height > pageHeight - footerHeight) {
          addNewPage()
        }
      }

      // Title
      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(22)
      pdf.setTextColor(30, 30, 30)
      const titleLines = pdf.splitTextToSize(topic, contentWidth)
      titleLines.forEach((line: string) => {
        checkPageBreak(10)
        pdf.text(line, margin, y)
        y += 10
      })

      // Underline
      y += 2
      pdf.setDrawColor(200, 200, 200)
      pdf.line(margin, y, pageWidth - margin, y)
      y += 10

      // Process content
      const lines = notes.split('\n')

      for (const line of lines) {
        const processedLine = processTextForPDF(line)

        // Headers
        if (line.startsWith('# ')) {
          checkPageBreak(12)
          y += 6
          pdf.setFont('helvetica', 'bold')
          pdf.setFontSize(18)
          pdf.setTextColor(20, 20, 20)
          const headerText = processedLine.slice(2)
          const headerLines = pdf.splitTextToSize(headerText, contentWidth)
          headerLines.forEach((l: string) => {
            checkPageBreak(8)
            pdf.text(l, margin, y)
            y += 8
          })
          y += 2
        }
        else if (line.startsWith('## ')) {
          checkPageBreak(10)
          y += 5
          pdf.setFont('helvetica', 'bold')
          pdf.setFontSize(14)
          pdf.setTextColor(40, 40, 40)
          const headerText = processedLine.slice(3)
          const headerLines = pdf.splitTextToSize(headerText, contentWidth)
          headerLines.forEach((l: string) => {
            checkPageBreak(7)
            pdf.text(l, margin, y)
            y += 7
          })
          y += 2
        }
        else if (line.startsWith('### ')) {
          checkPageBreak(8)
          y += 3
          pdf.setFont('helvetica', 'bold')
          pdf.setFontSize(12)
          pdf.setTextColor(50, 50, 50)
          const headerText = processedLine.slice(4)
          const headerLines = pdf.splitTextToSize(headerText, contentWidth)
          headerLines.forEach((l: string) => {
            checkPageBreak(6)
            pdf.text(l, margin, y)
            y += 6
          })
          y += 1
        }
        // Bullet points
        else if (line.match(/^[-*] /)) {
          pdf.setFont('helvetica', 'normal')
          pdf.setFontSize(11)
          pdf.setTextColor(60, 60, 60)
          const bulletText = processedLine.slice(2)
          const bulletLines = pdf.splitTextToSize(bulletText, contentWidth - 8)
          bulletLines.forEach((l: string, i: number) => {
            checkPageBreak(lineHeight)
            if (i === 0) {
              pdf.text('•', margin, y)
            }
            pdf.text(l, margin + 6, y)
            y += lineHeight
          })
        }
        // Numbered lists
        else if (line.match(/^\d+\. /)) {
          pdf.setFont('helvetica', 'normal')
          pdf.setFontSize(11)
          pdf.setTextColor(60, 60, 60)
          const match = line.match(/^(\d+)\. (.*)/)
          if (match) {
            const num = match[1]
            const listText = processTextForPDF(match[2])
            const listLines = pdf.splitTextToSize(listText, contentWidth - 10)
            listLines.forEach((l: string, i: number) => {
              checkPageBreak(lineHeight)
              if (i === 0) {
                pdf.text(`${num}.`, margin, y)
              }
              pdf.text(l, margin + 8, y)
              y += lineHeight
            })
          }
        }
        // Empty lines
        else if (line.trim() === '') {
          y += 3
        }
        // Regular paragraphs
        else {
          pdf.setFont('helvetica', 'normal')
          pdf.setFontSize(11)
          pdf.setTextColor(60, 60, 60)

          // Handle bold and italic in text
          let cleanText = processedLine
            .replace(/\*\*([^*]+)\*\*/g, '$1')
            .replace(/\*([^*]+)\*/g, '$1')
            .replace(/`([^`]+)`/g, '$1')

          const textLines = pdf.splitTextToSize(cleanText, contentWidth)
          textLines.forEach((l: string) => {
            checkPageBreak(lineHeight)
            pdf.text(l, margin, y)
            y += lineHeight
          })
        }
      }

      // Add footer to last page
      pdf.setFontSize(8)
      pdf.setTextColor(130, 130, 130)
      pdf.text('AI-generated notes for revision. Verify with official sources.', margin, pageHeight - 15)
      pdf.text('Generated by BloomGuide', margin, pageHeight - 10)
      pdf.text(`Page ${pageNum}`, pageWidth - margin - 15, pageHeight - 10)

      pdf.save(`${topic.replace(/[^a-zA-Z0-9]/g, '_')}_notes.pdf`)
    } catch (err) {
      console.error('PDF generation error:', err)
      downloadAsText()
    } finally {
      setIsDownloading(false)
    }
  }

  const downloadAsText = () => {
    const disclaimer = '\n\n---\nDisclaimer: These AI-generated notes are for revision purposes only and may not be comprehensive. Please verify with official sources and search for additional resources as needed.\n\nGenerated by BloomGuide'
    const blob = new Blob([notes + disclaimer], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${topic.replace(/[^a-zA-Z0-9]/g, '_')}_notes.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (isLoading) {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-2xl p-8 max-w-lg w-full text-center">
          <div className="w-16 h-16 border-4 border-teal-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-900">Generating Notes...</h3>
          <p className="text-gray-500 text-sm mt-2">Creating comprehensive study notes for {topic}</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
        <div className="bg-white rounded-2xl p-8 max-w-lg w-full text-center">
          <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <svg className="w-8 h-8 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </div>
          <h3 className="text-lg font-semibold text-gray-900">Failed to Generate Notes</h3>
          <p className="text-gray-500 text-sm mt-2">{error}</p>
          <div className="flex gap-3 justify-center mt-6">
            <button
              onClick={onClose}
              className="px-4 py-2 text-gray-600 hover:text-gray-800"
            >
              Cancel
            </button>
            <button
              onClick={() => {
                hasFetched.current = false
                fetchNotes()
              }}
              className="px-4 py-2 bg-teal-500 text-white rounded-lg hover:bg-teal-600"
            >
              Try Again
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl max-w-3xl w-full max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between bg-gradient-to-r from-teal-500 to-cyan-500">
          <div className="text-white">
            <p className="font-medium">Study Notes</p>
            <p className="text-xs opacity-90">{topic}</p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownloadPDF}
              disabled={isDownloading}
              className="flex items-center gap-2 px-4 py-2 bg-white/20 hover:bg-white/30 text-white rounded-lg text-sm font-medium transition-colors disabled:opacity-50"
            >
              {isDownloading ? (
                <>
                  <svg className="w-4 h-4 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                  </svg>
                  Generating...
                </>
              ) : (
                <>
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Download PDF
                </>
              )}
            </button>
            <button
              onClick={onClose}
              className="p-2 text-white/80 hover:text-white rounded-lg"
            >
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Notes Content - Using MathText for proper rendering */}
        <div className="flex-1 overflow-y-auto p-6" ref={notesRef}>
          <div className="prose prose-gray max-w-none">
            <MathText className="text-gray-700 leading-relaxed">{notes}</MathText>
          </div>
        </div>

        {/* Disclaimer Footer */}
        <div className="px-6 py-3 bg-amber-50 border-t border-amber-100">
          <p className="text-xs text-amber-700 flex items-start gap-2">
            <svg className="w-4 h-4 flex-shrink-0 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
            </svg>
            <span>
              <strong>Disclaimer:</strong> These AI-generated notes are for revision purposes only and may not be comprehensive.
              Please verify with official sources and search for additional resources as needed.
            </span>
          </p>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-gray-100 flex items-center justify-between bg-white">
          <button
            onClick={downloadAsText}
            className="text-sm text-gray-500 hover:text-gray-700 flex items-center gap-1"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Download as Markdown
          </button>
          <button
            onClick={onClose}
            className="px-6 py-2 bg-gray-900 text-white rounded-xl hover:bg-gray-800 font-medium"
          >
            Done
          </button>
        </div>
      </div>
    </div>
  )
}
